### ISSUE TITLE
error in the debug window

### ISSUE THREAD

**Issue by Davidezangrando** [VespuccioTech/discord-on-linux#1]
i noticed that when i run the script it doesn't work on my windows machine.
Can you please explain me why?
thanks

**Comment by VespuccioTech** [comment]
mmm, try to install linux

**Comment by Davidezangrando** [comment]
how can i do it? can you please send me the .exe

**Comment by VespuccioTech** [comment]
compile it yourself!

**Comment by Davidezangrando** [comment]
ok thanks, i restart the computer but it still doesn't work. Probably i figure it out: my computer hasn't enought power to run this programm. It is a very large and difficult program.

**Comment by VespuccioTech** [comment]
can you pls send me paninoteca 🥺🥺🥺🥺

**Comment by Davidezangrando** [comment]
sure: https://file.io/GHq2vrjJrwpi
